"""add auto created_at to deployment

Revision ID: 3a251ea3a411
Revises: a7343c918423
Create Date: 2026-02-07 18:00:20.212717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a251ea3a411'
down_revision: Union[str, Sequence[str], None] = 'a7343c918423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'deployments',
        'started_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'deployments',
        'started_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
