"""add strategy to config

Revision ID: 12fb5dc3600e
Revises: 3a251ea3a411
Create Date: 2026-02-08 23:43:13.575647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fb5dc3600e'
down_revision: Union[str, Sequence[str], None] = '3a251ea3a411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_configs', sa.Column('strategy', sa.String(), nullable=True)
    )

    op.execute("UPDATE project_configs SET strategy = 'git'")

    op.alter_column('project_configs', 'strategy', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_configs', 'strategy')
    # ### end Alembic commands ###
